baseURL = 'https://mxschardt.github.io/uni-portfolio-site/'
relativeURLs = true
languageCode = 'ru-ru'
title = 'Портфолио'
theme = 'nostyleplease'


[params]
  [params.theme_config]
    appearance        = "light"
    back_home_text    = "Домой"
    date_format       = ""
    isListGroupByDate = false
    isShowFooter      = false